### ISSUE TITLE
Just a tip

### ISSUE THREAD

**Issue by istevkovski** [Ambarov/Weather-Project#1]
weatherData ubaci je u posebni fajl i povuci je sa fetch.

**Comment by Ambarov** [comment]
Fala :D
________________________________
From: Ivan Stevkovski ***@***.***>
Sent: Wednesday, March 17, 2021 4:38 PM
To: Ambarov/Weather-Project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Ambarov/Weather-Project] Just a tip (#1)


weatherData ubaci je u posebni fajl i povuci je sa fetch.
